### ISSUE TITLE
mjml should auto complete attributes

### ISSUE THREAD

**Issue by connor4312** [mjmlio/vscode-mjml#16]
Before you open an issue, please check if a similar issue already exists or has been closed before.

## Expected behavior

I can type `<mj-text font-|`and get completions for the attributes

## Actual behavior

No completions are available :(

## Steps to reproduce the problem

  1. Type  `<mj-text font-|`
  1. Trigger completions

## Code sample

```
<mj-text font-|
```

## Screenshot / GIF

![](https://memes.peet.io/img/21-03-7313cd22-3a47-46ba-bc13-7809202bbde5.png)

## Specifications

  - VS Code version: 1.55.0-insiders
  - MJML extension version: 1.0.4
  - Operating system and version: Win 10

**Comment by Daniel-Knights** [comment]
I can make a merge request with this feature when I have some spare time today

**Comment by Daniel-Knights** [comment]
Opened a merge request here: #17
