### ISSUE TITLE
Option to automatically minify mj-group

### ISSUE THREAD

**Issue by fixallfixable** [mjmlio/vscode-mjml#20]
## Expected behavior
mj-group generated code should be automatically minified, by adding an option **similar** to "minify html output".

## Actual behavior
mj-group generated code creates a bug on iOS' gmail. The only way to fix this is to minify the code.
To do so, you need to enable the "minify html output" option, however I don't need to minify the entire file, because there are some things to do on the html after the export, and minifying it makes the code really hard to edit for my colleagues.

Is it possible to add some feature to minify only the code genereted by the mj-group?

Actually I'm doing it "manually" (by using external services to copy/past in code to minify) and there's not a Visual Studio Code plugin that can minify only the selected code (the only one avaiable works only for css)

Thanks

**Comment by iRyusa** [comment]
This behavior has been fixed in a https://github.com/mjmlio/mjml/pull/2049 so it's no longer needed.
