### ISSUE TITLE
Previewing relative images

### ISSUE THREAD

**Issue by matthew-dean** [mjmlio/vscode-mjml#23]
Right now, a tag like `<mj-hero background-url="assets/email-leaf-bg.png">` won't show the image in the preview window. It would be great to be able to do this.

**Comment by matthew-dean** [comment]
Note, this seems to work in `html-preview-vscode` (getting images relative to HTML file) https://github.com/tht13/html-preview-vscode/blob/ee44cd19f7abbaf5d1852cfd0b111c2b3d1fd909/src/features/previewContentProvider.ts#L126 so I'm not sure why it doesn't work in this context.

**Comment by iRyusa** [comment]
Does seem to work fine now in 2.x
