### ISSUE TITLE
[Feature Request] Pre-processor support for MJML preview

### ISSUE THREAD

**Issue by matthew-dean** [mjmlio/vscode-mjml#24]
It would be great if there was the ability to run MJML files through a pre- (or post-) processor before showing the HTML preview. That would allow data-binding template tags with custom data and would possible solve issues like: https://github.com/mjmlio/vscode-mjml/issues/23

**Comment by iRyusa** [comment]
Should be good in 2.x with preprocessors within mjml confi .js
