### ISSUE TITLE
When using a header include to define <mjml> preview window states "Active editor doesn't show a MJML document"

### ISSUE THREAD

**Issue by adamkdean** [mjmlio/vscode-mjml#28]
Before you open an issue, please check if a similar issue already exists or has been closed before.

## Expected behavior

I expect that the detection of an MJML document would take into account includes.

## Actual behavior

If the MJML tag is specified in an included template, the MJML isn't detected and preview window shows "Active editor doesn't show a MJML document".

## Steps to reproduce the problem

  1. Create header template with `<mjml>`
  2. Create footer template with `</mjml>`
  3. Create a main template with:
```html
<mj-include path="./header.mjml" />

<mj-body>
  x
</mjbody>

<mj-include path="./footer.mjml" />
```
  4. Look at preview window and despair

## Screenshot / GIF

<img width="322" alt="image" src="https://user-images.githubusercontent.com/1639527/175783367-ff5f71c2-144b-4943-a854-1c95453e6907.png">

## Specifications

  - VS Code version: 1.68.1
  - MJML extension version: 1.6.0

## Comments

~~The following works fine~~ but it just seemed like a bug to me that `mjml` being defined in the include wasn't checked for. To be fair, it is an edge case.

```html
<mjml>
  <mj-include path="./header.mjml" />

  <mj-section>
    x
  </mj-section>

  <mj-include path="./footer.mjml" />
</mjml>
```

Update: the above does not render correctly either, just rendering the header and nothing more.

**Comment by iRyusa** [comment]
You have no mj-body in your document that's why

**Comment by Sojaner** [comment]
@iRyusa would you take a look at [this demo](https://github.com/Sojaner/mjml-demo).
Both the MJML App can the node version render this correctly, but the VSCode extension shows the "Active editor doesn't show a MJML document" error for all the files. 
At least `index.mjml` and `about.mjml` files should be rendered fine, although node and MJML App render the header.mjml and footer.mjml files too.
