### ISSUE TITLE
Uncertainty of the VSCode plugin

### ISSUE THREAD

**Issue by davidsneighbour** [mjmlio/vscode-mjml#31]
Not sure how to formulate this, so let's just state the facts:

- https://documentation.mjml.io/#tooling links to https://github.com/mjmlio/vscode-mjml and https://marketplace.visualstudio.com/items?itemName=mjmlio.vscode-mjml
- THIS repo in the about section links to https://marketplace.visualstudio.com/items?itemName=attilabuti.vscode-mjml
- in the README.md of this repo the links also go to attilabuti.vscode-mjml

I understand, that there seems to be some kind of legacy-takeover by @mjmlio for the plugin, but even searching in VSCode for mjml ends me up with the following:

![20220814-21:26:43-Selection-001](https://user-images.githubusercontent.com/83281/184541562-e4736f6d-99c2-4a9b-b94f-639a99e27f98.png)

People might (and have, I did) ignore this version based on installs.

It would be nice, if this repo, IF it is the one official source for the plugin could somehow remove any ambiguity to the "old" plugin, maybe somehow add a paragraph about how it came about to be (forked the original plugin, etc) and the old plugin somehow could be removed or deprecated (VSCode offers a system where the old plugin can set some parameters in package.json and users get nudged to upgrade. 

If of course the old maintainer just disappeared this won't be possible. In that case this repo at least should loose all "official" looking links to the old repo with a legacy note instead of even in the about-section linking to the old repo. 

I am sure there can be done a little bit more to make this distinctively "the" repo for the MJML VSCode plugin... I actually forked the old repo myself because I thought there is no more current version and recent updates were missing. Let's make this one the main-one?

**Comment by iRyusa** [comment]
We have no control over this sadly, we should replace old url from this fork at least to make it clear that's the current maintained version we have

**Comment by gileri** [comment]
Hello, part of the issue is the link in the "About" section of this (mjmlio/vscode-mjml) repo that still links to the forked-from extension ([attilabuti.vscode-mjml](https://marketplace.visualstudio.com/items?itemName=attilabuti.vscode-mjml)). It should link to [mjmlio.vscode-mjml](https://marketplace.visualstudio.com/items?itemName=mjmlio.vscode-mjml) AFAIK.

**Comment by iRyusa** [comment]
Just open a PR about this we'll merge it quickly

**Comment by gileri** [comment]
It is not modifiable via a PR, a maintainer need to go on the Github web interface and change it by clicking on the cogwheel. Example on another repo :

![GH repository settings](https://user-images.githubusercontent.com/493438/187786862-fb73bdd1-9917-408b-a884-40dbe085095f.png)

**Comment by iRyusa** [comment]
It seems that it cannot be edited for official fork :/

**Comment by gileri** [comment]
Weird, I can on a fork such as [this one](https://github.com/gileri/based.cooking). Maybe there is a configuration issue in the MJML's Github organisation rights ?
