### ISSUE TITLE
MJML couldn't build the proper version of PhantomJS

### ISSUE THREAD

**Issue by rucksman** [mjmlio/vscode-mjml#38]
Pretty new to MJML. Tried to install the extension into my VSCode. Install completed without any problems. Wrote a very simple "Hello World" template in VSCode. Then tried to preview it in VSCode. Result:
`MJML couldn't build the proper version of PhantomJS. Restart VSCode in order to try it again.`

So I restartet VSCode, but the error appeared again.

**Comment by iRyusa** [comment]
You're not on this version, it only happen's when using Attila's original version

**Comment by tbunique** [comment]
I uninstalled and reinstalled this specific version of MJML VsCode extension and I still get this error message.
![image](https://github.com/mjmlio/vscode-mjml/assets/45557334/175a46f9-484e-4940-b315-c22b45888a78)

**Comment by Knappster** [comment]
Sadly I'm running into the same issue. Double checked I'm using the right extension.
`MJML couldn't build the proper version of PhantomJS. Restart VSCode in order to try it again.`

**Comment by sk-gara** [comment]
Same here. Can we reopen this issue?

**Comment by iRyusa** [comment]
What OS are you running ? Can you do some preview ?

**Comment by sk-gara** [comment]
Hi! 
Windows 10 and Debian 12.
What do you mean by doing some preview?

**Comment by iRyusa** [comment]
If you take a MJML file and doing a preview via the command palette does it
do anything ?

**Comment by sk-gara** [comment]
Ah! :)
In the preview pane appears the message "Active editor doesn't show a MJML document.", while vscode notifies: 
"MJML needs to be rebuilt for your current platform. Please wait for the installation to finish..."

This fails with "MJML couldn't build the proper version of PhantomJS. Restart VSCode in order to try it again."

**Comment by iRyusa** [comment]
Sorry to ask, but it was done on a MJML file right ?

It's so weird as Phantom is only used for screenshot. We maybe need to
remove this for now as phantom is no longer maintained anyway.

**Comment by sk-gara** [comment]
No problem :) But yeah, I'm testing on the demo mjml taken from the online editor.

**Comment by sk-gara** [comment]
Hey! I just had a moment to think about this issue and found something. It works when the source is an actual file.
I only opened a new tab and set the language to mjml before. I wasn't aware that this is how you're supposed to use it. Maybe it should say so explicitly in the description?
I imagine this restriction comes with the way the processor works?

**Comment by iRyusa** [comment]
I think we can do it for unsaved file but I guess it would mean to do some stuff to handle relative path (img, and so on...)

**Comment by sk-gara** [comment]
I'm okay with working with files for now. I just think there should be a line somewhere in the README.md to make it clear. 
A fileless preview and live editing would be nice of course. Maybe set a working directory in the settings where relative paths can be set for assets.
