### ISSUE TITLE
Option to insert external css file or code

### ISSUE THREAD

**Issue by nitin2953** [mjmlio/vscode-mjml#42]
## Feature suggestion

An option to insert external css file or mjml code for development purpose

## Use case

During development I use the design's image as `<body>`'s background to achieve near perfect result

## Code sample

```html
<mj-include path="../style.css" type="css" />
```

## Other information

Another toggle to choose weather to insert the css file or code in preview, generated html or both

**Comment by iRyusa** [comment]
This should work on 2.x
