### ISSUE TITLE
MJML couldn't build the proper version of PhantomJS. Restart VSCode in order to try it again.

### ISSUE THREAD

**Issue by sowinski** [mjmlio/vscode-mjml#48]
## Expected behavior

Install MJML in Visual Studio Code without an error

## Actual behavior

After installing MJML I get this error in a popup

`MJML couldn't build the proper version of PhantomJS. Restart VSCode in order to try it again.`

## Steps to reproduce the problem

  1. Install Linux Mint 21.3 (Virginia)
  1. Install Visual Studio Code 1.92.2 through Flatpak (Flathub)
  1. Run Visual Studio Code and install the MJML fork. (This repo)

**Comment by iRyusa** [comment]
Can you check you're not running the Attila's version ? (You should use the 2nd result when searching for mjml not the 1st one)

**Comment by sowinski** [comment]
Thank you for the fast response.

I use the second result as you can see here:
![Auswahl_014](https://github.com/user-attachments/assets/e4f06f64-4819-4a1e-bbb4-6492fe2c47c2)

**Comment by sowinski** [comment]
@iRyusa 

I use Linux Mint 21.3 (Virginia). The preview works well. What downsides do I have with this error?

**Comment by iRyusa** [comment]
You shouldn't be able to do screenshot. Idk if we should keep this feature as PhantomJS isn't supported anymore

**Comment by iRyusa** [comment]
Switch to 2.x branch this feature has been completely removed.
