### ISSUE TITLE
Cannot build source. Dependencies are very far out of date. PR available

### ISSUE THREAD

**Issue by rosskevin** [mjmlio/vscode-mjml#49]
Before you open an issue, please check if a similar issue already exists or has been closed before.

## Expected behavior

I expect to be able to build this from source.  No new tags, no new releases are listed on the repo page, but there were merges of PR's such as #47 which is what I need

## Actual behavior

```
~/D/vscode-mjml ❯❯❯ npm install

> vscode-mjml@1.0.6 postinstall
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.23.0
Found minimal version that qualifies engine range: 1.23.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45/src/vs/vscode.d.ts
Error installing vscode.d.ts: TypeError: Cannot set properties of null (setting 'Authorization')
npm ERR! code 1
npm ERR! path /Users/kross/Downloads/vscode-mjml
npm ERR! command failed
npm ERR! command sh -c node ./node_modules/vscode/bin/install
```

And checking the dependencies - they are very far out of date:

![SCR-20240905-pklq](https://github.com/user-attachments/assets/5652fce3-dd80-4b2f-911c-02c82c270f94)

## Steps to reproduce the problem

  1. npm install

## Screenshot / GIF

Please attach screenshot/gif if you consider them as helpful to understand/reproduce the issue.

![SCR-20240905-pmgo](https://github.com/user-attachments/assets/0d094128-c41f-4a5c-bc72-0109e91cacab)

## Specifications

  - VS Code version: 1.92.2
  - MJML extension version: `master` `0ffe95568452713f3f9ae70c4465b5344f7fd560`
  - Operating system and version: OSX 14.6.1

## Other information

I'm confused, a recently merged PR, very old tags, very old releases, VERY old dependencies.  There was a mention in #47 about a release this week, but there are no other branches....confused.

**Comment by iRyusa** [comment]
I have now the ownership of the extension so I should be able to update the version "soon". But my time is really limited for MJML so I do my best to handle support + continue dev on those projects.

**Comment by rosskevin** [comment]
Thank you @iRyusa 

I don't know vscode extensions, but I'll take a swing at updates and see if I can get you a PR that moves this forward a little.

It looks like this needs a `vscode` migration that is old enough, I had to use the wayback machine to find it!
http://web.archive.org/web/20210505205913/https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode

I'll see if I can get updates working.

**Comment by rosskevin** [comment]
PR pushed, changes were reasonably straightforward, but it needs reviewed due to may lack of experience in this area.

Now I'll see if I can run it!

**Comment by iRyusa** [comment]
Should be good now 👍
