### ISSUE TITLE
Link title attribute missing from exported HTML

### ISSUE THREAD

**Issue by alexhooley** [mjmlio/vscode-mjml#53]
Before you open an issue, please check if a similar issue already exists or has been closed before.

## Expected behavior

Adding a title attribute to mj-button should create a title attribute in the link when you export to HTML. 

This works in the live editor: https://mjml.io/try-it-live/Csf6LVoY5T
```html
<a href="https://mjml.io/" title="This is the title" style="display:inline-block;background:#414141;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:3px;" target="_blank">Hover over me</a>
```
## Actual behavior
Title attribute is missing in exported HTML and in the preview when using the VS Code extension:
```html
<a href="https://mjml.io/" style="display:inline-block;background:#414141;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:3px;" target="_blank">Hover over me</a>
```

## Steps to reproduce the problem

Compare the output of the following in the live editor vs the VS Code extension:

```html
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-button title="This is the title" href="https://mjml.io/">Hover over me</mj-button>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

## Code sample

```
Please provide a code snippet.
```

## Screenshot / GIF

Please attach screenshot/gif if you consider them as helpful to understand/reproduce the issue.

## Specifications

  - VS Code version: 1.93.1
  - MJML extension version: v1.0.6
  - Operating system and version: Ubuntu 24.04.1 LTS

## Other information

List any other information that is relevant to your issue.

**Comment by iRyusa** [comment]
Latest version should fix this i'm closing.
